# D3 : Numpy and Pandas
-  https://docs.python.org/3/library/index.html
-  https://numpy.org/
-  https://numpy.org/doc/stable
-  https://numpy.org/doc/stable/user/absolute_beginners.html

In [2]:
print(np.__version__)

1.24.3


In [3]:
#%% #numpy - array - same data type - numerical python
list1 = [1,2,3,5]
list1

[1, 2, 3, 5]

In [4]:
import numpy
print(numpy.array([10,20])) #list to numpy array
print(numpy.array([list1])) #list inside a list

[10 20]
[[1 2 3 5]]


In [5]:
import numpy as np   #shift + enter

In [6]:
np.arange(1,100,10)  #start, stop, setp

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [15]:
x=np.arange(start=1,stop=1000000,step=3)  #very large number series
print(x)
print(len(x))

[     1      4      7 ... 999991 999994 999997]
333333


In [16]:
np.sum(x)

-837557877

In [17]:
np.mean(x)

499999.0

In [18]:
np.std(x)

288674.84591837926

In [19]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.random.rand(5, 4)  # array of random nos betw 0 and 1 : shape of 3 rows x 4 cols

array([[0.39812635, 0.89312904, 0.93093054, 0.51781314],
       [0.11423573, 0.57325382, 0.94394496, 0.70784952],
       [0.76967518, 0.90490655, 0.58236023, 0.04764742],
       [0.75289088, 0.85677331, 0.33830791, 0.67613122],
       [0.28037565, 0.30425883, 0.41707523, 0.73939428]])

In [23]:
4%2

0

In [24]:
5%2

1

In [25]:
4%3

1

In [26]:
3%3

0

In [27]:
5%3

2

In [30]:
4%2 != 0

False

In [29]:
5%2

1

In [31]:
##  D3 Pandas
   https://pandas.pydata.org/
   https://pandas.pydata.org/docs/getting_started/index.html

In [32]:
import pandas as pd

In [34]:
name=["a","b","c","d","e"]
len(name)

5

In [35]:
age=np.random.randint(low=20, high=30, size=len(name), dtype=int)
age

In [36]:
['m','f','m','f','m']


['m', 'f', 'm', 'f', 'm']

NameError: name 'df' is not defined